# Gradient of Image

## import library

In [1]:
import numpy as np
import matplotlib.image as img
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.colors as colors

## load input image ('test.jpeg')

In [2]:
I0 = img.imread('test.jpeg')

In [3]:
I0

array([[[192,  97,  53],
        [183,  87,  45],
        [189,  94,  48],
        ...,
        [142, 194,  84],
        [111, 195,  84],
        [  1,   0,   8]],

       [[190,  94,  52],
        [190,  95,  51],
        [180,  84,  42],
        ...,
        [142, 195,  81],
        [116, 199,  85],
        [  0,   0,   4]],

       [[179,  86,  43],
        [191,  98,  55],
        [179,  87,  40],
        ...,
        [152, 202,  87],
        [115, 195,  80],
        [  3,   1,   4]],

       ...,

       [[134, 139,  55],
        [129, 141,  55],
        [136, 145,  66],
        ...,
        [168, 198, 164],
        [202, 212, 178],
        [  3,   5,  17]],

       [[133, 131,  46],
        [137, 140,  59],
        [123, 133,  47],
        ...,
        [183, 214, 172],
        [194, 187, 141],
        [  0,   1,   0]],

       [[135, 125,  38],
        [131, 124,  54],
        [122, 134,  32],
        ...,
        [173, 203, 165],
        [193, 172, 129],
        [  2,   1,   0]]

## check the size of the input image

In [4]:
# ++++++++++++++++++++++++++++++++++++++++++++++++++
# complete the blanks
#
num_row     = I0.shape[0]
num_column  = I0.shape[1]
num_channel = I0.shape[2]
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('number of rows of I0 = ', num_row)
print('number of columns of I0 = ', num_column)
print('number of channels of I0 = ', num_channel)

number of rows of I0 =  510
number of columns of I0 =  512
number of channels of I0 =  3


## convert the color image into a grey image
- take the average of the input image with 3 channels with respect to the channels into an image with 1 channel

In [11]:
# ++++++++++++++++++++++++++++++++++++++++++++++++++
# complete the blanks
#

I = np.mean(I0,axis=2)
    
    
num_row     = I.shape[0]
num_column  = I.shape[1]
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('number of rows of I = ', num_row)
print('number of columns of I = ', num_column)

number of rows of I =  510
number of columns of I =  512


In [12]:
I

array([[114.        , 105.        , 110.33333333, ..., 140.        ,
        130.        ,   3.        ],
       [112.        , 112.        , 102.        , ..., 139.33333333,
        133.33333333,   1.33333333],
       [102.66666667, 114.66666667, 102.        , ..., 147.        ,
        130.        ,   2.66666667],
       ...,
       [109.33333333, 108.33333333, 115.66666667, ..., 176.66666667,
        197.33333333,   8.33333333],
       [103.33333333, 112.        , 101.        , ..., 189.66666667,
        174.        ,   0.33333333],
       [ 99.33333333, 103.        ,  96.        , ..., 180.33333333,
        164.66666667,   1.        ]])

## normalize the converted image
- normalize the converted grey scale image so that its maximum value is 1 and its minimum value is 0

In [14]:
# ++++++++++++++++++++++++++++++++++++++++++++++++++
# complete the blanks
#

I = (I-np.min(I))/(np.max(I)-np.min(I))

#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('maximum value of I = ', np.max(I))
print('minimum value of I = ', np.min(I))

maximum value of I =  1.0
minimum value of I =  0.0


In [21]:
I.shape

(510, 512)

In [20]:
for i in range(I.shape[0]):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

## define a function to compute the derivative of input matrix in x(row)-direction

- forward difference : $ I[x+1, y] - I[x, y] $ 

In [24]:
def compute_derivative_x_forward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    for i in range(I.shape[0]-1):
        for j in range(I.shape[1]):
            D[i,j] = I[i+1,j] - I[i,j]

    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [26]:
compute_derivative_x_forward(I).shape

(510, 512)

- backward difference : $ I[x, y] - I[x-1, y] $ 

In [28]:
def compute_derivative_x_backward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    for i in range(1, I.shape[0]):
        for j in range(I.shape[1]):
            D[i,j] = I[i,j] - I[i-1,j]
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

- central difference : $ \frac{1}{2} \left( I[x+1, y] - I[x-1, y] \right)$ 

In [35]:
def compute_derivative_x_central(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    for i in range(1, I.shape[0]-1):
        for j in range(I.shape[1]):
            D[i,j] = 0.5*(I[i+1,j] - I[i-1,j])   
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [36]:
compute_derivative_x_central(I)

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.02225131,  0.01897906, -0.01636126, ...,  0.01374346,
         0.        , -0.00065445],
       [-0.0065445 ,  0.01832461,  0.01243455, ...,  0.0039267 ,
         0.00719895, -0.00065445],
       ...,
       [-0.00327225,  0.0091623 , -0.02028796, ...,  0.00850785,
        -0.01767016, -0.0039267 ],
       [-0.01963351, -0.0104712 , -0.03861257, ...,  0.00719895,
        -0.06413613, -0.01439791],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

## define a function to compute the derivative of input matrix in y(column)-direction

- forward difference : $ I[x, y+1] - I[x, y] $ 

In [37]:
def compute_derivative_y_forward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    for i in range(I.shape[0]):
        for j in range(I.shape[1]-1):
            D[i,j] = 0.5*(I[i,j+1] - I[i,j])   
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [32]:
compute_derivative_y_forward(I)

array([[-0.01767016,  0.0104712 ,  0.00327225, ..., -0.01963351,
        -0.24934555,  0.        ],
       [ 0.        , -0.01963351,  0.0104712 , ..., -0.0117801 ,
        -0.2591623 ,  0.        ],
       [ 0.02356021, -0.02486911,  0.01505236, ..., -0.03337696,
        -0.25      ,  0.        ],
       ...,
       [-0.00196335,  0.01439791, -0.05039267, ...,  0.04057592,
        -0.3710733 ,  0.        ],
       [ 0.01701571, -0.02159686, -0.00327225, ..., -0.03075916,
        -0.34096859,  0.        ],
       [ 0.00719895, -0.01374346,  0.00196335, ..., -0.03075916,
        -0.32133508,  0.        ]])

- backward difference : $ I[x, y] - I[x, y-1] $ 

In [34]:
def compute_derivative_y_backward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    for i in range(I.shape[0]):
        for j in range(1, I.shape[1]):
            D[i,j] = 0.5*(I[i,j] - I[i,j-1])   
        
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

- central difference : $ \frac{1}{2} \left( I[x, y+1] - I[x, y-1] \right)$ 

In [38]:
def compute_derivative_y_central(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    for i in range(I.shape[0]):
        for j in range(1, I.shape[1]-1):
            D[i,j] = 0.5*(I[i,j+1] - I[i,j-1])     
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

In [39]:
compute_derivative_y_central(I).shape

(510, 512)

## compute the norm of the gradient of the input image 

- $L_2^2$-norm of the gradient $ \left( \frac{\partial I}{\partial x}, \frac{\partial I}{\partial y} \right) $ is defined by $ \left( \frac{\partial I}{\partial x} \right)^2 + \left( \frac{\partial I}{\partial y} \right)^2 $

In [40]:
def compute_norm_gradient_central(I):
    
    norm_gradient = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    norm_gradient = compute_derivative_x_central(I)**2 + compute_derivative_y_central(I)**2 
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return norm_gradient

In [43]:
compute_norm_gradient_central(I).shape

(510, 512)

___

___

## functions for presenting the results

___

___

In [44]:
def function_result_01():
    
    plt.figure(figsize=(8,6))
    plt.imshow(I0)
    plt.show()

In [46]:
def function_result_02():
    
    plt.figure(figsize=(8,6))
    plt.imshow(I, cmap='gray', vmin=0, vmax=1, interpolation='none')
    plt.show()

In [47]:
def function_result_03():

    D = compute_derivative_x_forward(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(D, cmap='gray')
    plt.show()

In [ ]:
def function_result_04():

    D = compute_derivative_x_backward(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(D, cmap='gray')
    plt.show()

In [ ]:
def function_result_05():

    D = compute_derivative_x_central(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(D, cmap='gray')
    plt.show()

In [ ]:
def function_result_06():

    D = compute_derivative_y_forward(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(D, cmap='gray')
    plt.show()

In [ ]:
def function_result_07():

    D = compute_derivative_y_backward(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(D, cmap='gray')
    plt.show()

In [ ]:
def function_result_08():

    D = compute_derivative_y_central(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(D, cmap='gray')
    plt.show()

In [ ]:
def function_result_09():

    D = compute_norm_gradient_central(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(D, cmap='gray')
    plt.show()

In [ ]:
def function_result_10():

    D = compute_norm_gradient_central(I)
    
    plt.figure(figsize=(8,6))
    im = plt.imshow(D, cmap=cm.jet, norm=colors.LogNorm())
    plt.colorbar(im)
    plt.show()

In [ ]:
def function_result_11():

    D = compute_derivative_x_forward(I)

    value1 = D[0, 0]    
    value2 = D[-1, -1]    
    value3 = D[100, 100]    
    value4 = D[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)


In [ ]:
def function_result_12():

    D = compute_derivative_x_backward(I)

    value1 = D[0, 0]    
    value2 = D[-1, -1]    
    value3 = D[100, 100]    
    value4 = D[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)


In [ ]:
def function_result_13():

    D = compute_derivative_x_central(I)

    value1 = D[0, 0]    
    value2 = D[-1, -1]    
    value3 = D[100, 100]    
    value4 = D[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)


In [ ]:
def function_result_14():

    D = compute_derivative_y_forward(I)

    value1 = D[0, 0]    
    value2 = D[-1, -1]    
    value3 = D[100, 100]    
    value4 = D[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)


In [ ]:
def function_result_15():

    D = compute_derivative_y_backward(I)

    value1 = D[0, 0]    
    value2 = D[-1, -1]    
    value3 = D[100, 100]    
    value4 = D[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)


In [ ]:
def function_result_16():

    D = compute_derivative_y_central(I)

    value1 = D[0, 0]    
    value2 = D[-1, -1]    
    value3 = D[100, 100]    
    value4 = D[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)


In [ ]:
def function_result_17():

    D = compute_norm_gradient_central(I)

    value1 = D[0, 0]    
    value2 = D[-1, -1]    
    value3 = D[100, 100]    
    value4 = D[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)


___

___

# results

___

___

In [ ]:
number_result = 17

for i in range(number_result):
    title = '## [RESULT {:02d}]'.format(i+1)
    name_function = 'function_result_{:02d}()'.format(i+1)

    print('**************************************************')
    print(title)
    print('**************************************************')
    eval(name_function)